name: Generate docs for challenges

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate docs for challenges
        run: |
          bash genDoc.sh */
          bash getStats.sh
          { echo "## Played Challenges 🌟"; cat Played_Challenges/out } >> Played_Challenges/README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am 'Automated generation of docs for challenges'
          git push
