name: Generate docs for challenges

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      name: Generate docs for challenges
      run: |
        bash genDoc.sh */
        git config --global user.name 'Maurice Lim'
        git config --global user.email 'mau-mauricelim@users.noreply.github.com'
        git commit -am 'Automated generation of docs for challenges'
        git push
